### PR TITLE
feat: v5.3.0 (support apple silicon arm64)

### PR DESCRIPTION
**Pull request by starxg**
support windows and apple silicon.

image

### CODE REVIEW

**Comment by liaosunny123** [comment]
Application startup exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Fiddler.WebUi.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime, ILoggerFactory loggerFactory)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Fiddler.WebUi.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime, ILoggerFactory loggerFactory)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Fiddler.WebUi.Program.Main(String[] args)
   at Fiddler.WebUi.Program.<Main>(String[] args)

系统：win11

**Comment by starxg** [comment]
> Application startup exception: System.InvalidOperationException: Sequence contains no elements
> 
>    at System.Linq.ThrowHelper.ThrowNoElementsException()
> 
>    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
> 
>    at Fiddler.WebUi.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime, ILoggerFactory loggerFactory)
> 
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
> 
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
> 
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> 
>    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
> 
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
> 
>    at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
> 
> Unhandled exception. System.InvalidOperationException: Sequence contains no elements
> 
>    at System.Linq.ThrowHelper.ThrowNoElementsException()
> 
>    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
> 
>    at Fiddler.WebUi.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime, ILoggerFactory loggerFactory)
> 
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
> 
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
> 
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
> 
>    at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
> 
>    at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
> 
>    at Microsoft.AspNetCore.Hosting.WebHost.BuildApplication()
> 
>    at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
> 
>    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
> 
>    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
> 
>    at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
> 
>    at Fiddler.WebUi.Program.Main(String[] args)
> 
>    at Fiddler.WebUi.Program.<Main>(String[] args)
> 
> 
> 
> 系统：win11

https://github.com/msojocs/fiddler-everywhere-enhance#patch

**Comment by aTenb** [comment]
兄弟可以啊 居然在淘宝卖29.8一个

**Comment by msojocs** [comment]
> 兄弟可以啊 居然在淘宝卖29.8一个

声明：我没卖钱，其他人不知道。

**Comment by enaske** [comment]
They added a new Protection on 5.7.1 it now detects Upstream Proxies. (The way we patch Fiddler I think)

**Comment by msojocs** [comment]
> 兄弟可以啊 居然在淘宝卖29.8一个

wc，大哥原来你说的是这个提交者，我才发现是TA在卖。

**Comment by aTenb** [comment]
> > 兄弟可以啊 居然在淘宝卖29.8一个
> 
> wc，大哥原来你说的是这个提交者，我才发现是TA在卖。

哈哈 你后知后觉了 我就是说他啊 非常有实力 就是不愿意分享给我们用了

**Pull request merged**
